data_path: '/import/c4dm-04/cv/IDMT_dataset/IDMT-SMT-AUDIO-EFFECTS/IDMT-SMT-AUDIO-EFFECTS/'
data:
  frame_sz: 1024
  hop: 64
  mono: True
  fs: 16000
train:
  lr: 0.01
  batch: 32
  iterations: 1000

