data_path: '/import/c4dm-04/cv/fxdataset/'
data:
  frame_size: 1024
  hop_size: 64
  mono: True
  fs: 16000
  suffix: '.wav'
  separator: '-'
train:
  lr: 0.01
  batch: 32
  iterations: 1000
  n_epochs: 100
  optim: Adam
  patience: 15
  val_split: 0.1
  test_split: 0.2

