data_path: '/import/c4dm-04/cv/fxdataset/'
data:
  frame_size: 1024
  hop_size: 64
  mono: True
  fs: 16000
  suffix: '.wav'
  separator: '-'
train:
  lr: 0.0001
  batch: 32
  iterations: 1000
  n_epochs: 50
  n_epochs_supervised: 50
  optim: Adam
  patience: 20
  val_split: 0.1111111111111115
  test_split: 0.2

